version: '3'
services:
  api:
    image: 'bretts89/sourcey-api'
    mem_limit: 300m
    hostname: sourcey-api
    ports:
      - "80:5000"
    environment:
      - PORT=5000
      - MONGO_URI=$MONGO_URI
      - JWT_SECRET=$JWT_SECRET
